import { SidebarProvider } from "@/components/ui/sidebar";
import ProfileSideBar from "@/features/settings/components/profile-sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function Layout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <SidebarProvider className="flex-1 min-h-0 max-w-7xl m-auto">
            <ProfileSideBar />
            {children}
        </SidebarProvider>

    );
}
